### ISSUE TITLE
Ubuntu GPU 环境下多进程运行时内存增长问题

### ISSUE THREAD

**Issue by iminders** [iminders/tbase#6]
系统环境

Ubuntu 18.04
GPU: GTX 1080
Memory: 8G

运行命令： `python3 -m  tbase.run --num_env 2`

错误信息：
`
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/run.py", line 56, in <module>
    main()
  File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/run.py", line 50, in main
    agent.learn()
  File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/agents/ddpg/agent.py", line 152, in learn
    sample_size=self.args.sample_size)
  File "/home/ubuntu/gopath/src/github.com/iminders/tbase/tbase/agents/ddpg/agent.py", line 63, in explore
    worker.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/usr/lib/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds
    False, False, None)
OSError: [Errno 12] Cannot allocate memory
Segmentation fault (core dumped)
`

**Comment by iminders** [comment]
@iminders 
用小一点的网络，测试确定内存是不断增涨，还是正常的通讯所需要的临时内存

**Comment by iminders** [comment]
https://github.com/iminders/tbase/pull/20

使用小的 net size， RAM, GPU-Memory 都没有下降！

LSTM_MLP(
  (rnn): LSTM(30, 20)
  (fc1): Linear(in_features=20, out_features=20, bias=True)
  (fc2): Linear(in_features=20, out_features=2, bias=True)
  (activation): Tanh()
)
LSTM_Merge_MLP(
  (rnn): LSTM(30, 20)
  (fc1): Linear(in_features=2, out_features=20, bias=True)
  (fc2): Linear(in_features=20, out_features=10, bias=True)
  (fc3): Linear(in_features=30, out_features=1, bias=True)
  (activation): Tanh()
)

**Comment by iminders** [comment]
#20

单进程内存占用情况： 
- RAM:  1.61 G
- GPU:  0.54 G

2个探索进程内存占用情况：
- RAM：1.67 G - 5.34 G 之间波动，然后 memory error 
- GPU:   0.54 G - 1.56 G 之间波动

**Comment by iminders** [comment]
moved into: https://github.com/tradingAI/tbase/issues/7
